version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - "5319:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp:
    depends_on:
      - db
    image: wordpress
    links:
      - db
    ports:
      - "5318:80"
    working_dir: /var/www/html
    volumes:
     - ./:/var/www/html/wp-content/themes/salvia-theme
     - ./.data/plugins/:/var/www/html/wp-content/plugins
     - ./.data/uploads/:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
  
  wpcli:
    image: wordpress:cli
    volumes_from:
      - wp
    links:
      - db
    entrypoint: wp  
    command: "--info"